# Generated by Django 3.2.12 on 2022-02-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_order_orderitem_shop_shopitem_shopoptiontype_shopoptionvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('WAITING', 'WAITING'), ('PREPARATION', 'PREPARATION'), ('READY', 'READY'), ('DELIVERED', 'DELIVERED'), ('CANCEL', 'CANCEL')], max_length=255, null=True),
        ),
    ]
