# Generated by Django 3.2.12 on 2022-02-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_bill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
